### ISSUE TITLE
Question: Default dependency injection vs that-depends

### ISSUE THREAD

**Issue by SyntaxRules-avant** [modern-python/litestar-sqlalchemy-template#11]
This is an opinion question so feel free to treat it as such.

> OC (Inversion of Control) container built on [that-depends](https://github.com/modern-python/that-depends/) - my DI framework

Is there a reason you picked `that-depends` instead of the litestar built in dependency injection? [Link to litestar DI](https://docs.litestar.dev/2/usage/dependency-injection.html)

I'm getting started on a new project and want to hear your thoughts about the tradeoffs. Thanks!

**Comment by lesnik512** [comment]
@SyntaxRules-avant Hi, I can write some thoughts)
Disadvantages of Litestar built in DI:
1. If you have some consumers or cronjobs or other separate parts of application, than you can't use LiteStar DI in them. Otherwise, Litestar DI can be enough
2. Also, it can be simpler to test with DI framework, because build in DI only suited for API tests

**Comment by lesnik512** [comment]
As a matter of fact, I'm writing another DI framework right now https://github.com/modern-python/modern-di

it will have litestar support soon

**Comment by SyntaxRules-avant** [comment]
Cool, I'll check it out. Thanks for the quick reply!
